# Generated by Django 2.2 on 2020-02-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200224_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemodel',
            options={'ordering': ('create_time',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',)},
        ),
    ]
