# Generated by Django 2.2 on 2020-02-24 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionaldata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_ad', to=settings.AUTH_USER_MODEL),
        ),
    ]
